### ISSUE TITLE
the collected recovery is not loaded

### ISSUE THREAD

**Issue by n0-n4-m3** [azwhikaru/Action-Recovery-builder#43]
![изображение](https://user-images.githubusercontent.com/67657503/214238103-8f357548-9843-4035-826f-70ea60398e33.png)
After a successful build of vendorboot or recovery, nothing loads on my github, most likely the problem is in the env in the Recovery Build.yml, however, nothing loads
Recovery Build.yml:
```
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Device: ${{ github.event.inputs.DEVICE_NAME }}
          Target: ${{ github.event.inputs.BUILD_TARGET }}.img
      env:
        GITHUB_TOKEN: ${{ secrets.TEST.TEST }}
```
![изображение](https://user-images.githubusercontent.com/67657503/214238710-907b47a9-63ad-4d38-b600-e464325de8c7.png)
